# Principle components

### Principle:
Principle components are the axis on to which the data can be projected as in real weorld case most of the feature are constant or corelated and do not introduce new direction and thus can be projected on to a reduced dimension  

In [1]:
import numpy as np

In [2]:
X = np.array([
    [2, 4],
    [4, 2],
    [6, 8],
    [8, 6]
])

In [3]:
X_centered= X - X.mean(axis = 0)
X_centered

array([[-3., -1.],
       [-1., -3.],
       [ 1.,  3.],
       [ 3.,  1.]])

In [4]:
U,s,Vt = np.linalg.svd(X_centered)

In [5]:
c1 = Vt.T[:, 0]
c2 = Vt.T[:, 1]

In [6]:
c1,c2

(array([0.70710678, 0.70710678]), array([-0.70710678,  0.70710678]))

### Reducing to d dimensions


In [7]:
Wd = Vt[:,:2]
Xproj = X.dot(Wd)
Xproj

array([[-1.41421356,  4.24264069],
       [ 1.41421356,  4.24264069],
       [-1.41421356,  9.89949494],
       [ 1.41421356,  9.89949494]])

### Using scikit learn

In [14]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
Xproj =  pca.fit_transform(X)

In [15]:
Xproj

array([[-2.82842712,  1.41421356],
       [-2.82842712, -1.41421356],
       [ 2.82842712,  1.41421356],
       [ 2.82842712, -1.41421356]])

After fitting the PCA transformer to the dataset, its components_ attribute holds the
transpose of Wd (e.g., the unit vector that defines the first principal component is
equal to pca.components_.T[:, 0]

In [16]:
pca.components_

array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]])

In [17]:
Wd.T

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

Another useful piece of information is the explained variance ratio of each principal
component, available via the explained_variance_ratio_ variable

In [18]:
pca.explained_variance_ratio_

array([0.8, 0.2])

The ratio indi‐
cates the proportion of the dataset’s variance that lies along each principal compo‐
nent