In [1]:
from sklearn.datasets import make_moons
X, y = make_moons(n_samples=1000, noise=0.05)
from sklearn.mixture import GaussianMixture
gm  = GaussianMixture(n_components=3, n_init = 10) 
gm.fit(X)

,n_components,3
,covariance_type,'full'
,tol,0.001
,reg_covar,1e-06
,max_iter,100
,n_init,10
,init_params,'kmeans'
,weights_init,None
,means_init,None
,precisions_init,None
,random_state,None


In [2]:
gm.weights_

array([0.19652803, 0.59425767, 0.20921429])

In [3]:
gm.means_

array([[-0.76240748,  0.54264308],
       [ 0.4881269 ,  0.26510008],
       [ 1.72650398, -0.06671683]])

In [4]:
gm.covariances_

array([[[ 0.04271412,  0.0541293 ],
        [ 0.0541293 ,  0.08268659]],

       [[ 0.16926774, -0.10357786],
        [-0.10357786,  0.29243969]],

       [[ 0.0614014 ,  0.06583845],
        [ 0.06583845,  0.087037  ]]])

In [5]:
gm.converged_

True

In [7]:
gm.predict(X)

array([1, 1, 2, 2, 2, 1, 1, 1, 2, 1, 2, 2, 0, 0, 1, 2, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 2, 2, 1, 0, 1, 0, 1, 1, 0, 2, 0, 0, 1,
       1, 0, 1, 2, 0, 1, 1, 1, 1, 2, 0, 2, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 2, 1, 1, 1, 1, 2, 0, 0, 1, 2, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 2, 2, 0, 1, 0, 1, 2, 1, 0, 1, 1, 1, 1, 1, 2, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 2,
       1, 1, 2, 1, 1, 2, 1, 1, 0, 1, 1, 1, 2, 1, 1, 1, 2, 1, 2, 2, 2, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 1, 0, 1, 2, 1, 1, 0, 2, 1, 1, 2,
       1, 1, 1, 2, 2, 2, 0, 1, 0, 1, 1, 1, 2, 0, 2, 0, 1, 2, 1, 1, 1, 1,
       1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 2, 2, 1, 1, 1, 2, 0, 0, 0,
       0, 1, 2, 1, 1, 2, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 0,
       2, 0, 2, 0, 1, 1, 1, 1, 2, 1, 0, 1, 2, 0, 1, 1, 2, 0, 0, 1, 1, 2,
       1, 0, 2, 0, 1, 2, 1, 1, 1, 1, 1, 1, 1, 0, 1,

In [8]:
gm.predict_proba(X)

array([[6.26548045e-003, 9.93734520e-001, 3.51356444e-137],
       [3.51222858e-021, 1.00000000e+000, 4.27402333e-090],
       [4.95461753e-248, 2.41144940e-002, 9.75885506e-001],
       ...,
       [6.86921496e-003, 9.93130785e-001, 6.43233260e-138],
       [4.04118760e-185, 9.92405905e-001, 7.59409504e-003],
       [9.91616104e-001, 8.38389629e-003, 2.02004127e-167]],
      shape=(1000, 3))

A Gaussian mixture model is a generative model, meaning you can sample new
instances from it (note that they are ordered by cluster index

In [10]:
X_new, y_new = gm.sample(6)

In [11]:
X_new

array([[ 0.2175639 , -0.36179029],
       [ 0.27042986, -0.06963104],
       [ 1.20640463, -0.98430686],
       [ 1.18929436, -0.42894223],
       [ 1.86316719,  0.09606026],
       [ 1.45567471, -0.46112004]])

In [12]:
y_new

array([1, 1, 1, 1, 2, 2])

### Anomaly detection using GMM

In [14]:
import numpy as np
densities = gm.score_samples(X)
density_threshold = np.percentile(densities, 4)
anomalies = X[densities < density_threshold]

In [15]:
anomalies

array([[ 1.88342398,  0.47468372],
       [ 2.10585665,  0.53859271],
       [-0.27765955,  0.95175469],
       [-1.00341676, -0.00369676],
       [-0.23829619,  1.01821245],
       [-0.27664388,  0.9805596 ],
       [ 1.99292206,  0.52475239],
       [-0.14372333,  1.09639533],
       [-0.26210281,  0.99234908],
       [-0.27648249,  0.87678826],
       [-0.23449122,  1.02038408],
       [-0.18427715,  0.98324371],
       [-0.27911171,  0.94487789],
       [-0.92781282,  0.06682395],
       [-0.31941539,  0.91587095],
       [ 1.90941031,  0.41173282],
       [ 1.99257981,  0.46111913],
       [-0.17263877,  1.01785231],
       [-0.98026339, -0.08523183],
       [ 1.96529032,  0.46485976],
       [-0.96622316,  0.01359522],
       [-0.27044385,  0.99193536],
       [-0.96770156,  0.03738694],
       [ 1.92060407,  0.45373873],
       [-1.01352622, -0.01433432],
       [-0.30814223,  0.92521637],
       [-0.24200766,  0.94149822],
       [-0.96228965,  0.01873304],
       [ 2.0539262 ,