# Exercise 3.1
Try to build a classifier for the MNIST dataset that achieves over 97% accuracy
on the test set. Hint: the KNeighborsClassifier works quite well for this task;
you just need to find good hyperparameter values (try a grid search on the
weights and n_neighbors hyperparameters).

In [2]:
from sklearn.datasets import fetch_openml
data = fetch_openml('mnist_784', version=1)

In [3]:
y = data.target.astype(int)

In [4]:
X = data['data']

In [5]:
X.shape

(70000, 784)

In [6]:
X.head()

pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
0       0       0       0       0       0       0       0       0       0   
1       0       0       0       0       0       0       0       0       0   
2       0       0       0       0       0       0       0       0       0   
3       0       0       0       0       0       0       0       0       0   
4       0       0       0       0       0       0       0       0       0   

   pixel10  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0        0  ...         0         0         0         0         0         0   
1        0  ...         0         0         0         0         0         0   
2        0  ...         0         0         0         0         0         0   
3        0  ...         0         0         0         0         0         0   
4        0  ...         0         0         0         0         0         0   

   pixel781  pixel782  pixel783  pixel784  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 784 columns]

In [7]:
X_train,X_test,y_train,y_test = X[:60000], X[60000:], y[:60000], y[60000:]

In [8]:
X_train.head()

pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
0       0       0       0       0       0       0       0       0       0   
1       0       0       0       0       0       0       0       0       0   
2       0       0       0       0       0       0       0       0       0   
3       0       0       0       0       0       0       0       0       0   
4       0       0       0       0       0       0       0       0       0   

   pixel10  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0        0  ...         0         0         0         0         0         0   
1        0  ...         0         0         0         0         0         0   
2        0  ...         0         0         0         0         0         0   
3        0  ...         0         0         0         0         0         0   
4        0  ...         0         0         0         0         0         0   

   pixel781  pixel782  pixel783  pixel784  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 784 columns]

In [9]:
X_train,X_test,y_train,y_test = X[:60000], X[60000:], y[:60000], y[60000:]

In [26]:
from sklearn.preprocessing import  StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

In [23]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()

In [92]:
knn.fit(X_train_scaled, y_train)

KNeighborsClassifier()

In [93]:
pred = knn.predict(scaler.transform(X_test))

In [94]:
pred

array([7, 2, 1, ..., 4, 5, 6], shape=(10000,))

##### Evaluating the model

In [95]:
from sklearn.metrics import f1_score

In [96]:
y.value_counts()

class
1    7877
7    7293
3    7141
2    6990
9    6958
0    6903
6    6876
8    6825
4    6824
5    6313
Name: count, dtype: int64

In [97]:
f1_score(y_test, pred, average='macro')

0.9436860218534469

In [98]:
from sklearn.model_selection import cross_val_predict
preds_folds = cross_val_predict(knn, X_train_scaled,y_train,cv = 3, n_jobs = -1)

In [99]:
preds_folds

array([3, 0, 4, ..., 5, 6, 8], shape=(60000,))

In [100]:
from sklearn.model_selection import cross_val_score
pred_folds_scores = cross_val_score(knn, X_train_scaled,y_train,cv = 3, n_jobs = -1)

In [101]:
pred_folds_scores

array([0.9376, 0.9411, 0.9424])

##### Hyperparamter Turning (Adjusting the weights and n_neighbors)

In [24]:
from sklearn.model_selection import GridSearchCV
param_grid = {
    'n_neighbors': [3,4,5,6,7],
    'weights': ['uniform', 'distance', 'callable']
}
grid = GridSearchCV(knn, param_grid=param_grid, cv = 3, n_jobs = -1)

In [25]:
grid

GridSearchCV(cv=3, estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'n_neighbors': [3, 4, 5, 6, 7],
                         'weights': ['uniform', 'distance', 'callable']})

In [104]:
grid.fit(X_train_scaled,y_train)

c:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning: 
15 fits failed out of a total of 45.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
9 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
  File "c:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py", li

GridSearchCV(cv=3, estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'n_neighbors': [3, 4, 5, 6, 7],
                         'weights': ['uniform', 'distance', 'callable']})

In [109]:
grid.best_params_

{'n_neighbors': 4, 'weights': 'distance'}

In [110]:
grid_pred = grid.predict(scaler.transform(X_test))

In [111]:
f1_score(y_test, grid_pred, average = 'macro')

0.9483697634110856

In [115]:
grid.score(scaler.transform(X_test), y_test)

0.9489

In [112]:
from sklearn.metrics import accuracy_score
print("The Accuracy Score: ", accuracy_score(y_test,grid_pred ))

The Accuracy Score:  0.9489


Write a function that can shift an MNIST image in any direction (left, right, up,
or down) by one pixel.5 Then, for each image in the training set, create four shif‐
ted copies (one per direction) and add them to the training set. Finally, train your
best model on this expanded training set and measure its accuracy on the test set.
You should observe that your model performs even better now! This technique of
artificially growing the training set is called data augmentation or training set
expansion

You can use the shift() function from the scipy.ndimage.interpolation module. For example,
shift(image, [2, 1], cval=0) shifts the image two pixels down and one pixel to the right.

In [10]:
from scipy.ndimage.interpolation import shift
import pandas as pd
def change_direction(X,y):
    X_augment = []
    y_augment = []

    directions = ['left' , 'right' ,'up', "down"]

    for dir in directions:
        for i in range(len(X)):
            image = X.iloc[i].to_numpy().reshape(28,28)
            label = y.iloc[i]
            if dir.lower() == 'left':
                shifted = shift(image,[0,-1],cval = 0)
            elif dir.lower() == 'right':
                shifted = shift(image,[0,1],cval = 0)
            elif dir.lower() == 'up':
                shifted = shift(image,[-1,0],cval = 0)
            elif dir.lower() == 'down':
                shifted = shift(image,[-1,0],cval = 0)

            image = shifted.flatten()
            X_augment.append(image)
            y_augment.append(label)
    
    return X_augment, y_augment


C:\Users\DELL\AppData\Local\Temp\ipykernel_15408\304881283.py:1: DeprecationWarning: Please import `shift` from the `scipy.ndimage` namespace; the `scipy.ndimage.interpolation` namespace is deprecated and will be removed in SciPy 2.0.0.
  from scipy.ndimage.interpolation import shift


In [11]:
X_augment, y_augment = change_direction(X,y)

In [12]:
len(X_augment),len(y_augment)

(280000, 280000)

In [19]:
import numpy as np
new_X = np.concatenate((X.to_numpy(), X_augment), axis=0)

In [20]:
new_y = np.concatenate((y.to_numpy(), y_augment), axis=0)

In [22]:
new_X_train, new_X_test, new_y_train, new_y_test = new_X[:330000],new_X[330000:], new_y[:330000],new_y[330000:]

##### Evaluating the mdoel on the new data

In [27]:
new_X_train = scaler.transform(new_X_train)

c:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [ ]:
from sklearn.model_selection import cross_val_score
cross_val_score(knn, new_X_train, new_y_train,cv = 3, n_jobs = 1)